export const getUrlIconWeather = (conditioncode?: number) => {
  switch (conditioncode) {
    case 1000:
      return "/assets/icons/weather/sun.png";
    case 1003:
      return "/assets/icons/weather/cloudy.png";
    case 1006:
      return "/assets/icons/weather/cloudy.png";
    case 1009:
      return "/assets/icons/weather/cloudy.png";
    case 1030:
      return "/assets/icons/weather/mist.png";
    case 1063:
      return "/assets/icons/weather/rain.png";
    case 1066:
      return "/assets/icons/weather/snow.png";
    case 1069:
      return "/assets/icons/weather/snow.png";
    case 1072:
      return "/assets/icons/weather/snow.png";
    case 1087:
      return "/assets/icons/weather/thunder.png";
    case 1114:
      return "/assets/icons/weather/snow.png";
    case 1117:
      return "/assets/icons/weather/snow.png";
    case 1135:
      return "/assets/icons/weather/mist.png";
    case 1147:
      return "/assets/icons/weather/mist.png";
    case 1150:
      return "/assets/icons/weather/mist.png";
    case 1153:
      return "/assets/icons/weather/mist.png";
    case 1168:
      return "/assets/icons/weather/mist.png";
    case 1171:
      return "/assets/icons/weather/mist.png";
    case 1180:
      return "/assets/icons/weather/rain.png";
    case 1183:
      return "/assets/icons/weather/rain.png";
    case 1186:
      return "/assets/icons/weather/rain.png";
    case 1189:
      return "/assets/icons/weather/rain.png";
    case 1192:
      return "/assets/icons/weather/rain.png";
    case 1195:
      return "/assets/icons/weather/rain.png";
    case 1198:
      return "/assets/icons/weather/rain.png";
    case 1201:
      return "/assets/icons/weather/rain.png";
    case 1204:
      return "/assets/icons/weather/rain.png";
    case 1207:
      return "/assets/icons/weather/rain.png";
    case 1210:
      return "/assets/icons/weather/rain.png";
    case 1213:
      return "/assets/icons/weather/rain.png";
    case 1216:
      return "/assets/icons/weather/rain.png";
    case 1219:
      return "/assets/icons/weather/snow.png";
    case 1222:
      return "/assets/icons/weather/snow.png";
    case 1225:
      return "/assets/icons/weather/snow.png";
    case 1237:
      return "/assets/icons/weather/snow.png";
    case 1240:
      return "/assets/icons/weather/rain.png";
    case 1243:
      return "/assets/icons/weather/rain.png";
    case 1246:
      return "/assets/icons/weather/rain.png";
    case 1249:
      return "/assets/icons/weather/rain.png";
    case 1252:
      return "/assets/icons/weather/rain.png";
    case 1255:
      return "/assets/icons/weather/snow.png";
    case 1258:
      return "/assets/icons/weather/snow.png";
    case 1261:
      return "/assets/icons/weather/snow.png";
    case 1264:
      return "/assets/icons/weather/snow.png";
    case 1273:
      return "/assets/icons/weather/thunder.png";
    case 1276:
      return "/assets/icons/weather/thunder.png";
    case 1279:
      return "/assets/icons/weather/thunder.png";
    case 1282:
      return "/assets/icons/weather/thunder.png";
    default:
      return "/assets/icons/weather/sun.png";
  }
};
